# Generated by Django 4.2.7 on 2023-12-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
